worker_num: 0
TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {hue: [-1.5, 1.5, 0.5], saturation: [0.95, 1.05, 0.5], contrast: [0.95, 1.05, 0.5], brightness: [0.95, 1.05, 0.5], count: 2}  # 随机颜色失真，可选的OP
    - RandomExpand: {ratio: 1.15, fill_value: [123.675, 116.28, 103.53]}
    - RandomDeMorie: {prob: 1.0}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  batch_size: 16
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: true


EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    - RandomDeMorie: {prob: 1.0}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 32
  shuffle: false
  drop_last: false


TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}
    - RandomDeMorie: {prob: 1.0}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false
