_BASE_: [
  '../../datasets/voc_mura_com.yml',
  '../../runtime.yml',
  '_base_/optimizer_500e_high.yml',
  '_base_/yolov8_cspdarknet.yml',
  '_base_/yolov8_reader_high_aug.yml',
]
depth_mult: 0.67
width_mult: 0.75

log_iter: 50
snapshot_epoch: 5
weights: output/yolov8_m_500e_coco/model_final
pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov8_m_500e_coco.pdparams
classwise: True

YOLOv8CSPDarkNet:
  last_stage_ch: 768 # The actual channel is int(768 * width_mult), not int(1024 * width_mult) as in YOLOv5


TrainReader:
  batch_size: 16 # default 8 gpus, total bs = 128
