eval_height: &eval_height 512
eval_width: &eval_width 512
eval_size: &eval_size [*eval_height, *eval_width]

worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 100
  sample_transforms:
    - Decode: {}
    - RandomDistort: {hue: [-1.5, 1.5, 0.5], saturation: [0.95, 1.05, 0.5], contrast: [0.95, 1.05, 0.5], brightness: [0.95, 1.05, 0.5], count: 2}
    #- RandomExpand: {ratio: 1.15, fill_value: [123.675, 116.28, 103.53]}
    - RandomDeMorie: {prob: 1.0}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [448, 480, 512, 544, 576, 608, 640], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    #- NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - NormalizeImage: {mean: [0.0, 0.0, 0.0], std: [1.0, 1.0, 1.0], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], 
                      #anchors: [[10, 15], [24, 36], [72, 42], [35, 87], [102, 96], [60, 170], [220, 125], [128, 222], [264, 266]],
                      anchors: [[492, 6], [7, 491],  [465, 10], [13, 481], [477, 14], [21, 505],  [510, 21], [508, 44],  [52, 496]],
                      downsample_ratios: [32, 16, 8]}
  batch_size: 32
  shuffle: true
  drop_last: true
  mixup_epoch: -1 #500
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - RandomDeMorie: {prob: 1.0}
    #- NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - NormalizeImage: {mean: [0.0, 0.0, 0.0], std: [1.0, 1.0, 1.0], is_scale: True}
    - Permute: {}
  batch_size: 32

TestReader:
  inputs_def:
    image_shape: [3, *eval_height, *eval_width]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.0, 0.0, 0.0], std: [1.0, 1.0, 1.0], is_scale: True}
    #- NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
