_BASE_: [
  '../../datasets/voc_mura_line.yml',
  '../../runtime.yml',
  './_base_/ppyolo_mbv3_large.yml',
  './_base_/optimizer_1x.yml',
  './_base_/ppyolo_reader.yml',
]

log_iter: 100
snapshot_epoch: 2
weights: output/ppyolo_mbv3_large_coco/model_final
eval_weights: output/ppyolo_mbv3_large_coco/best_model
classwise: True

TrainReader:
  inputs_def:
    num_max_boxes: 90
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {hue: [-2.5, 2.5, 0.5], saturation: [0.90, 1.10, 0.5], contrast: [0.90, 1.10, 0.5], brightness: [0.90, 1.10, 0.5], count: 2}  # 随机颜色失真，可选的OP
    - RandomExpand: {ratio: 1.15, fill_value: [123.675, 116.28, 103.53]} # 随机Canvas填充，可选的OP 
    - RandomDeMorie: {prob: 0.75}
    - RandomFlip: {}  # 随机左右翻转，默认概率0.5，可选的OP
  batch_transforms:
    - BatchRandomResize:
        target_size: [416, 448, 480, 512, 544, 576, 608, 640]
        random_size: True
        random_interp: True
        keep_ratio: False
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 90}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
    - Gt2YoloTarget:
        anchor_masks: [[3, 4, 5], [0, 1, 2]]
        anchors: [[11, 18], [34, 47], [51, 126], [115, 71], [120, 195], [254, 235]]
        #anchors: [[6, 497], [505, 11], [11, 500], [20, 508], [509, 35], [44, 506]]
        downsample_ratios: [32, 16]
        iou_thresh: 0.25
        num_classes: 6
  batch_size: 32
  mixup_epoch: 200
  shuffle: true
  allow_empty: false

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [512, 512], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 8

TestReader:
  inputs_def:
    image_shape: [3, 512, 512]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [512, 512], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1

epoch: 270

LearningRate:
  base_lr: 0.005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 162
    - 216
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
