worker_num: 4
eval_height: &eval_height 512
eval_width: &eval_width 512
eval_size: &eval_size [*eval_height, *eval_width]

TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomDistort: {hue: [-2.5, 2.5, 0.5], saturation: [0.90, 1.10, 0.5], contrast: [0.90, 1.10, 0.5], brightness: [0.90, 1.10, 0.5], count: 2}  # 随机颜色失真，可选的OP
    - RandomExpand: {ratio: 1.15, fill_value: [123.675, 116.28, 103.53]} # 随机Canvas填充，可选的OP 
    - RandomDeMorie: {prob: 0.75}
    - RandomFlip: {}  # 随机左右翻转，默认概率0.5，可选的OP
  batch_transforms:
    - BatchRandomResize: {target_size: [416, 448, 480, 512, 544, 576, 608, 640], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
    - PadGT: {}
  batch_size: 32
  shuffle: true
  drop_last: true
  use_shared_memory: true
  collate_batch: true
  allow_empty: false

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - RandomDeMorie: {prob: 0.75}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 8

TestReader:
  inputs_def:
    image_shape: [3, *eval_height, *eval_width]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *eval_size, keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1
